### PR TITLE
🌋 Refactor exception handling and pass GraphQL Errors from Client Operations

### LINKED ISSUE #32: Pass GraphQL Errors From Client Operations
### Expected vs. Actual Behavior

At the moment, [GraphQL Client Operations](https://github.com/specklesystems/Core/blob/master/Core/Api/Client.GraphqlClientOperations.cs) all return standard string errors (eg "Could not create stream"). It would be more helpful if the specific GraphQL errors could be passed on in the message so you don't have to dig all the way into core to find out what the actual error is.

### Reproduction Steps & System Config (win, osx, web, etc.)

Make any bad GraphQL request using `Client.GraphqlClientOperations`.

### Proposed Solution (if any)

Pass the actual GraphQL errors into the `GraphQLException`.

### PR DESCRIPTION
**Pull request by izzylys**
## Description

Previously, exceptions were thrown by calling `CaptureAndThrow( new SpeckleException( ... ) )` or `CaptureAndThrow( new GraphQLException( ... ) )`. Additionally, GraphQL Errors were not passed on to the dev when a `GraphQLException` was thrown.

This refactor changes the behaviour so exceptions are captured on construction and should be thrown like any other exception.
```cs
throw new SpeckleException("Something went wrong 😢", log: true, level: SentryLevel.VerySad)
```

- closes #32 

--- 

## Key Changes

1. Exceptions are captured in the constructors. Default is `log = true` and default log level is `Info`:
```cs
    public SpeckleException(string message, bool log = true, SentryLevel level = SentryLevel.Info ) : base(message)
    {
      if (log)
        Log.CaptureException(this, level);
    }
```

2. the GraphQL errors are now passed along to the dev (via a `SpeckleException` - the `GraphQLException` has been removed):
```cs
    public SpeckleException(string message, GraphQLError[ ] errors, bool log = true,
      SentryLevel level = SentryLevel.Info) : base(message)
    {
      GraphQLErrors = errors.Select(error => new KeyValuePair<string, object>("error", error.Message)).ToList();
      if (log)
        Log.CaptureException(this, extra: GraphQLErrors);
    }
```

3. `TaskCancelledException`s are never captured
```cs
    public static void CaptureAndThrow(Exception e)
    {
      if ( !( e is TaskCanceledException ) )
        CaptureException(e);
      throw e;
    }
```

4. `AggregateException`s are unpacked and the inner exceptions are captured individually
unpacked aggregate exceptions in the sentry dashboard

5. `CaptureAndThrow` has been removed 
5. `SpeckleException` with `InnerException` will be ignored and not captured

```cs
    public SpeckleException(string message, Exception inner, bool log = true, SentryLevel level = SentryLevel.Info)
         : base(message, inner)
    {
      if (inner is SpeckleException)
        return;
      if (log)
        Log.CaptureException(this);
    }
```

### Additional Details

- GraphQL exceptions are no longer being double reported

- All generic `System.Exception`s that we were throwing have been converted to `SpeckleException`s and are being logged. We can revisit this and weed out / adjust log levels if we find this is too much and we don't care about some of these. 

- `ReflectionTypeLoadException`s when loading kits are ignored.

### Log Levels

Regarding log levels, I'm not too clear on the strategy here. At the moment, basically everything is info. The things I have elevated are:

1. `🔴 Error`: critical core stuff (exceptions in `Operations.Send`/`Receive` and the `BaseObjectSerialiser`) 
2. `🔴 Error`: unable to generate account id (`Account.id`)
3. `🟡 Warning`: inheriting from `SelectKitComponentBase` in grasshopper
4. `🟡 Warning`: failure to load kits

I'm not sure about a lot of other stuff tho. eg exceptions from GraphQL queries are handled properly everywhere they are used, so I have this as `Info`. However, if a dev is using it from Core and not handling possible exceptions then for them this is an `Error`. Should all GraphQL errors then be `Error` level? 

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

This changes the behaviour of the `SpeckleException` but the rest of `speckle-sharp` has also been refactored to reflect this.

## How has this been tested?

- [x] Manual Tests (what did you do?)

triggered errors manually and checked sentry dashboard to ensure errors are being reported as expected

### CODE REVIEW

**Comment by izzylys** [comment]
- [ ] this terrible overlay that isn't changing for light mode (i'm sorryyyyy)
image
- [ ] button to remove streams you don't have a local account for / don't have access to

File: Core/Core/Logging/SpeckleException.cs [hunk 1]
```diff
@@ -1,4 +1,9 @@
 ﻿using System;
```
Comment (didimitrie) [inline Core/Core/Logging/SpeckleException.cs:1]: What i was thunking here was that we don't really need two exception classes, and could just have one! Perhaps it's not worth it though. Here's my 0.002c re what I had in mind: 

```cs

public SpeckleException( string message, bool log = false) { ... } 

public SpeckleException( GraphQLError[ ] gqlErrors, bool log = false) { ... } 

```

Not sure the `GraphQLException` does anything special in the way we handle it, but IIRC, it doesn't?

Comment (didimitrie) [reply Core/Core/Logging/SpeckleException.cs:1]: Ofc, internally: 
```cs
public SpeckleException( string message, bool log = false) 
{ 
   // ...
   if(log) 
   { 
     Log.Capture() etc.   
   }
} 
```

I'm not sure if we catch globally unhandled exceptions in .NET?

Comment (teocomi) [reply Core/Core/Logging/SpeckleException.cs:1]: > I'm not sure if we catch globally unhandled exceptions in .NET?

They are usually swallowed by the host applications.

**Comment by izzylys** [comment]
PR description is being updated as I go so have a read to get an idea of where this is at. suggestions welcome!

**Comment by AlanRynne** [comment]
Regarding the `CaptureAndThrow` magic and the handling of `SpeckleExceptions`. My only concern with that is that we have no way of knowing, as a developer, if this exact exception has already been captured at a lower level.

I would propose the `CaptureAndThrow` behaviour to be:

1. Capture the original exception for Sentry, whatever that is, so that it is properly logged with its name 👍🏻 
2. Create a new **unlogged** `SpeckleException` to which we can assign the "original" exception as the `InnerException`.
3. Throw the `SpeckleException` instead.

This way, you could assume that if you encounter a `SpeckleException` you can already assume that it has been handled in Sentry (either logged or ignored...whatever), and we also have access to the original Exception further on if necessary.

**Comment by teocomi** [comment]
Agree with what you describe @AlanRynne ! And I think @didimitrie 's suggestion was to have 1 & 2 in the constructor of the `SpeckleException`.

File: Core/Core/Api/GraphQL/Client.Subscriptions.Commit.cs [hunk 2]
```diff
@@ -42,8 +42,7 @@ public void SubscribeCommitCreated(string streamId)
       }
       catch (Exception e)
       {
-        Log.CaptureException(e);
-        throw e;
+        Log.CaptureAndThrow(e);
```
Comment (teocomi) [inline Core/Core/Api/GraphQL/Client.Subscriptions.Commit.cs:45]: Was this one missed? There's a few more below...

**Comment by izzylys** [comment]
cool yes I've incorporated Alan's suggestion! see the notes section of the PR

can you clarify what you mean? 1. and 2. are the constructors

File: Core/Core/Logging/SpeckleException.cs [hunk 3]
```diff
@@ -1,36 +1,37 @@
...
-  {
-    public GraphQLException()
+    public SpeckleException(string message, bool log = false, SentryLevel level = SentryLevel.Info ) : base(message)
     {
+      if (log)
+        Log.CaptureException(this, level);
     }
 
-    public GraphQLException(string message) : base(message)
+    public SpeckleException(string message, GraphQLError[ ] errors, bool log = false,
```
Comment (teocomi) [inline Core/Core/Logging/SpeckleException.cs:22]: Minor comment: maybe log could default to true, since that's the majority of the cases. But it's probably too much hassle to update it, so no biggie!

File: Core/Core/Logging/SpeckleException.cs [hunk 4]
```diff
@@ -1,36 +1,37 @@
...
+      SentryLevel level = SentryLevel.Info) : base(message)
     {
+      GraphQLErrors = errors.Select(error => new KeyValuePair<string, object>("error", error.Message)).ToList();
+      if (log)
+        Log.CaptureException(this, extra: GraphQLErrors);
     }
 
-    public GraphQLException(string message, Exception inner)
+    public SpeckleException(string message, Exception inner, bool log = false, SentryLevel level = SentryLevel.Info)
```
Comment (teocomi) [inline Core/Core/Logging/SpeckleException.cs:30]: We should probably check if `inner is SpeckleException` and in that case ignore it as it's already been reported before.

File: Core/Core/Logging/SpeckleException.cs (hunk 3 above)
Comment (didimitrie) [reply Core/Core/Logging/SpeckleException.cs:22]: i'd agree re too much hassle :D

File: Objects/Objects/ObjectsKit.cs [hunk 5]
```diff
@@ -84,7 +84,7 @@ public ISpeckleConverter LoadConverter(string app)
         }
         else
         {
-          throw new SpeckleException($"Converter for {app} was not found in kit {basePath}");
+          throw new SpeckleException($"Converter for {app} was not found in kit {basePath}", level: Sentry.Protocol.SentryLevel.Warning);
```
Comment (teocomi) [inline Objects/Objects/ObjectsKit.cs:87]: Should log be true?

Comment (didimitrie) [reply Objects/Objects/ObjectsKit.cs:87]: yep agreed on this - if we end up here something seriously borked in the installation process...

File: Core/Core/Logging/SpeckleException.cs (hunk 3 above)
Comment (teocomi) [reply Core/Core/Logging/SpeckleException.cs:22]: > cool yes I've incorporated Alan's suggestion! see the notes section of the PR
> 
> can you clarify what you mean? the code snippets in 1. and 2. are the constructors

Yup, soz I replied before looking at the code! I think the only bit missing then is https://github.com/specklesystems/speckle-sharp/pull/278#discussion_r586563243

**Review by didimitrie — COMMENTED** [review]
beyond @teocomi 's last point, all good 2 go :)

File: Core/Core/Logging/SpeckleException.cs (hunk 3 above)
Comment (izzylys) [reply Core/Core/Logging/SpeckleException.cs:22]: rip soz I assumed there was a reason for dim's suggestion in his comment to default `log = false` but I guess not 😅

File: Core/Core/Api/GraphQL/Client.Subscriptions.Commit.cs (hunk 2 above)
Comment (izzylys) [reply Core/Core/Api/GraphQL/Client.Subscriptions.Commit.cs:45]: in what way? i'm using `CaptureAndThrow` here on purpose if that's what you mean
