### PR TITLE
gergo/removeDeprecatedUserQueryAgain

### LINKED ISSUE #2430: regression(Navisworks): Basepoint transforms not applying
Unclear when this stopped working. 

This is a key interoperability feature for host applications unable to handle real-world coordinates.

### LINKED ISSUE #2665: bug(Navisworks): Small models (with few objects) may trigger Divide by zero errors
To reduce the UI drag of the Progress Bar running on the main thread, we use an interval that is a constant of 1% of the total objects for conversion or traversal. Small models containing fewer than 100 elements were triggering divided by zero errors on the Modulus check for updating progress.

### PR DESCRIPTION
**Pull request by gjedlicska**
- Core/update deps2 (#2564)
- Add version for TopSolid Connector (Core-kit) (#2607)
- deprecate(rhino): removes Rhino BIM functionality (#2602)
- Refactor(Revit): Abstract previously received objects logic into interface (#2596)
- fix(rhino): missing application ids in nested block instances (#2616)
- chore(core): updates sentry, avalonia and other packages minor verisons (#2624)
- fix(dui): #2605 handles exceptions during search (#2639)
- refractor: revit tests (#2648)
- Fix(Revit): make all tests pass (#2622)
- Feat(Revit) : Add support for 2024 (#2649)
- Chore(connectors): Removed usages of deprecated overloads (#2652)
- Feat(Revit): send cropped meshes from view filter (#2650)
- feat(core): Traversal optimisation by avoiding unnecessary traversal of dynamic properties (#2651)
- feature(Navisworks): Enhance Selection Handling and Hierarchy Population (#2641)
- Add Speckle Navisworks Connector README.md (#2661)
- fix(csi): Add polygonmesher to copy to kit task (#2659)
- feat(Navisworks): Retry Sending already converted objects. Implements #2668 (#2670)
- fix(Navisworks): Reset ConverterContext on each send. Fixes #2430 (#2667)
- fix(Navisworks): Division by zero errors on small models. Fixes #2665 (#2666)
- feat(autocadcivil): adds extension dictionaries to speckle conversions (#2675)
- fix(rhino): Fixes family rotation by computing the angle between the insertion plane and world X (#2677)
- fix(rhino): mapper wall logic for extrusions (#2678)
- Fix(Revit) : fix element delete (#2680)
- feat(Navisworks): Conversion Cache (#2682)
- feat(Archicad): Time profiler (#2634)
- feat(dui): check if stream exists (#2625)
- removed deprecated user query and use the new activeUser one

## Checklist:

- [ ] My pull request follows the guidelines in the [Contributing guide](https://github.com/specklesystems/speckle-server/blob/main/CONTRIBUTING.md)?
- [ ] My pull request does not duplicate any other open [Pull Requests](../../pulls) for the same update/change?
- [ ] My commits are related to the pull request and do not amend unrelated code or documentation.
- [ ] My code follows a similar style to existing code.
- [ ] I have added appropriate tests.
- [ ] I have updated or added relevant documentation.

### CODE REVIEW

File: Core/Core/Credentials/AccountManager.cs [hunk 1]
```diff
@@ -107,7 +107,7 @@ private static async Task<UserServerInfoResponse> GetUserServerInfo(string token
       var request = new GraphQLRequest
       {
         Query =
-          @"query { user { id name email company avatar streams { totalCount } commits { totalCount } } serverInfo { name company adminContact description version} }"
+          @"query { activeUser { id name email company avatar streams { totalCount } commits { totalCount } } serverInfo { name company adminContact description version} }"
```
Comment (AlanRynne) [inline Core/Core/Credentials/AccountManager.cs:110]: This is fine, but we also have to modify (or duplicate+obsolete) the `UserServerInfoResponse` so that it contains an `activeUser` field instead of a `user` field, or the query will succeed but the user will be null.

**Review by AlanRynne — CHANGES_REQUESTED** [review]
👇🏼 Just one thing. We may want to create `ActiveUserServerInfoResponse` and flag `UserInfoResponse` as obsolete instead of renaming a property willy-nilly.
